apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-kubernetes-provider
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-kubernetes-provider
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-kubernetes-provider
subjects:
  - kind: ServiceAccount
    # CRITICAL: This hash matches v0.12.1 exactly
    name: provider-kubernetes-6ef2ebb6f1db
    namespace: crossplane-system