apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgres-instance
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    crossplane.io/xrd: xpostgresinstances.database.bizmatters.io
spec:
  mode: Resources
  compositeTypeRef:
    apiVersion: database.bizmatters.io/v1alpha1
    kind: XPostgresInstance
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  
  resources:
    # Connection Secret - creates secret with claim-specified name
    # This ensures workloads depend on the claim contract, not CNPG implementation details
    # The secret copies username/password from app-provided credentials secret (from SSM)
    - name: connection-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: placeholder-secret
                namespace: placeholder
              type: Opaque
              stringData:
                endpoint: ""
                port: "5432"
                database: "postgres"
              # username and password are patched from app-provided credentials secret via references
          references:
            # Copy username from app-provided credentials secret
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                namespace: placeholder
                name: placeholder-credentials
                fieldPath: data.username
              toFieldPath: data.username
            # Copy password from app-provided credentials secret
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                namespace: placeholder
                name: placeholder-credentials
                fieldPath: data.password
              toFieldPath: data.password
          providerConfigRef:
            name: kubernetes-provider
      patches:
        # Secret name from connectionSecretName field
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecretName
          toFieldPath: spec.forProvider.manifest.metadata.name
        # Namespace from claim
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        # Reference namespace for credentials secret
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.references[0].patchesFrom.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.references[1].patchesFrom.namespace
        # Reference the app-provided credentials secret
        - type: FromCompositeFieldPath
          fromFieldPath: spec.credentialsSecretName
          toFieldPath: spec.references[0].patchesFrom.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.credentialsSecretName
          toFieldPath: spec.references[1].patchesFrom.name
        # Set endpoint (FQDN) using claim name and namespace
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.claimRef.name
              - fromFieldPath: spec.claimRef.namespace
            strategy: string
            string:
              fmt: "%s-rw.%s.svc.cluster.local"
          toFieldPath: spec.forProvider.manifest.stringData.endpoint
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # CNPG Cluster
    - name: cnpg-cluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: postgresql.cnpg.io/v1
              kind: Cluster
              metadata:
                name: placeholder
                namespace: placeholder
              spec:
                instances: 1
                imageName: ghcr.io/cloudnative-pg/postgresql:16
                storage:
                  size: 20Gi
                  storageClass: local-path
                # Enable superuser access so CNPG creates a password for postgres user
                enableSuperuserAccess: true
                bootstrap:
                  initdb:
                    database: postgres
                    # CNPG uses the 'username' from the secret as the database owner
                    # Secret must have 'username' and 'password' keys
                    # Do NOT set 'owner' here - let CNPG use the username from secret
                    secret:
                      name: placeholder-credentials
                # Node affinity to schedule on worker nodes with database label
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: workload.bizmatters.dev/databases
                              operator: In
                              values:
                                - "true"
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "250m"
                  limits:
                    memory: "2Gi"
                    cpu: "1000m"
          providerConfigRef:
            name: kubernetes-provider
      patches:
        # Namespace from claim
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        
        # Cluster name - use claim name for predictable naming
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        
        # Credentials secret - use app-provided secret for database bootstrap
        - type: FromCompositeFieldPath
          fromFieldPath: spec.credentialsSecretName
          toFieldPath: spec.forProvider.manifest.spec.bootstrap.initdb.secret.name
        
        # Size-based resource patches
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.manifest.spec.resources.requests.memory
          transforms:
            - type: map
              map:
                small: "256Mi"
                medium: "512Mi"
                large: "1Gi"
        
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.manifest.spec.resources.limits.memory
          transforms:
            - type: map
              map:
                small: "1Gi"
                medium: "2Gi"
                large: "4Gi"
        
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.manifest.spec.resources.requests.cpu
          transforms:
            - type: map
              map:
                small: "250m"
                medium: "500m"
                large: "1000m"
        
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.manifest.spec.resources.limits.cpu
          transforms:
            - type: map
              map:
                small: "1000m"
                medium: "2000m"
                large: "4000m"
        
        # Storage size patch
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageGB
          toFieldPath: spec.forProvider.manifest.spec.storage.size
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%dGi"
        
        # Version patch
        - type: FromCompositeFieldPath
          fromFieldPath: spec.version
          toFieldPath: spec.forProvider.manifest.spec.imageName
          transforms:
            - type: string
              string:
                type: Format
                fmt: "ghcr.io/cloudnative-pg/postgresql:%s"
      
      # Connection details - extract from CNPG-generated secret
      connectionDetails:
        - name: username
          type: FromConnectionSecretKey
          fromConnectionSecretKey: username
        - name: password
          type: FromConnectionSecretKey
          fromConnectionSecretKey: password
        - name: database
          type: FromConnectionSecretKey
          fromConnectionSecretKey: dbname
        - name: host
          type: FromConnectionSecretKey
          fromConnectionSecretKey: host
        - name: port
          type: FromConnectionSecretKey
          fromConnectionSecretKey: port
        - name: endpoint
          type: FromValue
          value: ""  # Will be patched from status
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"
