---
# Intelligence workloads automatically scheduled on worker nodes
# Node labels are defined in bootstrap/talos/nodes/worker01/config.yaml
# When worker joins, it automatically gets: workload.bizmatters.dev/intelligence=true

# Qdrant - Database, requires worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: intelligence
spec:
  template:
    spec:
      nodeSelector:
        workload.bizmatters.dev/intelligence: "true"  # Specific to intelligence workloads
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist  # Never schedule on control plane
---
# Qdrant MCP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-mcp
  namespace: intelligence
spec:
  template:
    spec:
      nodeSelector:
        workload.bizmatters.dev/intelligence: "true"
---
# GitHub Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-readonly-agent
  namespace: intelligence
spec:
  template:
    spec:
      nodeSelector:
        workload.bizmatters.dev/intelligence: "true"
---
# Librarian Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarian-agent
  namespace: intelligence
spec:
  template:
    spec:
      nodeSelector:
        workload.bizmatters.dev/intelligence: "true"
