apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sandbox-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/zerotouch-platform/zerotouch-platform
    targetRevision: HEAD
    path: temp-docs/repo/agent-sandbox/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-sandbox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3