apiVersion: ENC[AES256_GCM,data:ZUc=,iv:0snAl1ZsqiKaqGEFYStEq0WZe7dvBeLVTfdkPgFrNuY=,tag:DG/VDRttwa6eUPX1K5oJ6Q==,type:str]
kind: ENC[AES256_GCM,data:L1M0c0hG,iv:el78aUP/1Yc3WqytnGdEGu5oCQQTpeyyMSENuRio9Zs=,tag:r7wqwe4rASuNLVkHQo/oPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Rgx+1tNkcosT8Q==,iv:u68eZasuruSLlDxpYWfxmsJbYWSlBGWJ5nV9vpbmakw=,tag:7Pp1XT703iQNwF0/6MXjOQ==,type:str]
    namespace: ENC[AES256_GCM,data:Dv5iZGN2Uy53yfNW,iv:ID8q9t4CXB0ca6Xhni0X9mSG8c6iAH1WP7Yb7zBmyK8=,tag:HVSzCew4Kt3TpDz4dRYK5Q==,type:str]
type: ENC[AES256_GCM,data:DADhNrBv,iv:3S0UruvuSfXJk00toU7Tk5tifaAPoLiAc7p482l1CnA=,tag:3KbRUx4U0dbIKu5/mJwBbw==,type:str]
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:7ikM5Po5rXb14FG1nkUpiCw05A+kr6/tGKX7OCH4lc3aV4DqZ0n9ZQ==,iv:KAdB2c4/4tsgni7tSSpWDZDJxt6LNAXraPtNiyOf4sk=,tag:SJTo5LHlStwhK6TxOzmGrg==,type:str]
sops:
    age:
        - recipient: age1xncpcm2hjlszlgmyx7wf5u2w23h05mfscugcw34pany3akss7pgqe9mhqu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaDdIendncEQvUkhjK1Yx
            bktxL1AxZ0lMdjJPYU81NDZhQXVYS01OUTM0Cks4U1JhUjJwUGM5RGkrS3dNaVp4
            T0tucjBBRElxcXUzN3BOcEVpSnpuVVkKLS0tIEF1dXBXdnA4aXFvWG0wbnlMbWVj
            Q0VnMmhYc3lnVVh5ckNXVy9MOGtWT1EKSGCgfnJHNOWdLH+BqCRT4OgojF4E3Hx5
            Sm9sQnUsBT5/DB3X54/gJIDwPrtq539xQ9giWURgxYjfd2c1zKaejg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T07:38:20Z"
    mac: ENC[AES256_GCM,data:/OpwPtEsdUSAUmulu+BZGC7rLDFrww2Xg7RK4VQTfV2ZoZDch/QxRUDld8W/QnpfYdE9C3wlolm1S6thooj3RNajHg2Lzy/tJvUA2VEpR30QCt7LbRcSEgj1vma1aXvuNxzPGs5b51PYDrxh1O4XDwJT92fnrU/Lp5ZZ3lK6jGs=,iv:5i74nw45RAUyfHJRMPE29pI9MxztHDXbnfDEI9HLOvg=,tag:/EDbICn0Ffi+GPZa3Pd/2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
