apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-gateway-api
  labels:
    app.kubernetes.io/name: cilium-gateway-api
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: zerotouch-platform
rules:
# Gateway API resources
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - grpcroutes
  - tlsroutes
  - tcproutes
  - udproutes
  - referencegrants
  - backendtlspolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  - grpcroutes/status
  - tlsroutes/status
  - tcproutes/status
  - udproutes/status
  verbs:
  - update
  - patch
# Secrets for TLS certificates
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# Services for LoadBalancer provisioning
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-gateway-api
  labels:
    app.kubernetes.io/name: cilium-gateway-api
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: zerotouch-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium-gateway-api
subjects:
- kind: ServiceAccount
  name: cilium
  namespace: kube-system